### ISSUE TITLE
list account commands: cannot unmarshal object into Go struct field

### ISSUE THREAD

**Issue by andypiper** [mcornick/clilol#12]
Running 0.9.2 on Fedora 37 (Linux)

Tried `clilol list account addresses`

```
Error: json: cannot unmarshal object into Go struct field listAccountAddressesOutput.response of type []struct { Address string "json:\"address\""; Message string "json:\"message\""; Registration struct { Message string "json:\"message\""; UnixEpochTime int "json:\"unix_epoch_time\""; ISO8601Time time.Time "json:\"iso_8601_time\""; RFC2822Time string "json:\"rfc_2822_time\""; RelativeTime string "json:\"relative_time\"" } "json:\"registration\""; Expiration struct { Expired bool "json:\"expired\""; WillExpire bool "json:\"will_expire\""; UnixEpochTime int "json:\"unix_epoch_time\""; ISO8601Time time.Time "json:\"iso_8601_time\""; RFC2822Time string "json:\"rfc_2822_time\""; RelativeTime string "json:\"relative_time\"" } "json:\"expiration\""; Preferences struct { IncludeInDirectory string "json:\"include_in_directory\""; ShowOnDashboard string "json:\"show_on_dashboard\""; Statuslog struct { MastodonPosting bool "json:\"mastodon_posting\"" } "json:\"statuslog\"" } "json:\"preferences\"" }
```

A similar error is returned for `list account sessions`

**Comment by mcornick** [comment]
Thanks for being the first person to report a bug!

It looks like the response from the server is not something the JSON parser can comprehend. Either there are keys missing/present that should be present/absent, or it's just not valid JSON at all. In the first case, I may need to update the code to account for the missing/presnet key. And in the second case, I should probably handle the error with a more user-friendly response.

Either way, I can't reproduce this with my account.

I'd like to see what clilol is getting back from the server, but I don't want to see all the private details about your account. So I've written a script that will get the underlying JSON, but redact all the values that I know about, leaving just the JSON structure. Can you do this:

1) install curl and jq, if you haven't already
2) Run the script at https://gist.github.com/mcornick/172222a66b3b4efac5cb1959cc20b719, substituting your API key and email
3) look over the output and make sure all the data is redacted (edit if necessary)
4) send me the output (either here or in another gist)

Thanks!

**Comment by andypiper** [comment]
Nice! Thanks for doing the work to clean/redact the output in the script here.

Here's the output:

```json
{
  "request": {
    "status_code": 200,
    "success": true
  },
  "response": [
    {
      "address": "redacted",
      "message": "redacted",
      "registration": {
        "message": "redacted",
        "unix_epoch_time": 0,
        "iso_8601_time": "redacted",
        "rfc_2822_time": "redacted",
        "relative_time": "redacted"
      },
      "expiration": {
        "expired": false,
        "will_expire": false,
        "unix_epoch_time": 0,
        "iso_8601_time": "redacted",
        "rfc_2822_time": "redacted",
        "relative_time": "redacted"
      },
      "preferences": {
        "statuslog": {
          "mastodon_posting": "redacted"
        },
        "include_in_directory": "redacted",
        "show_on_dashboard": "redacted"
      }
    },
    {
      "address": "redacted",
      "message": "redacted",
      "registration": {
        "message": "redacted",
        "unix_epoch_time": 0,
        "iso_8601_time": "redacted",
        "rfc_2822_time": "redacted",
        "relative_time": "redacted"
      },
      "expiration": {
        "expired": false,
        "will_expire": false,
        "unix_epoch_time": 0,
        "iso_8601_time": "redacted",
        "rfc_2822_time": "redacted",
        "relative_time": "redacted"
      },
      "preferences": {
        "include_in_directory": "redacted",
        "show_on_dashboard": "redacted",
        "statuslog": {
          "mastodon_posting": "redacted"
        }
      }
    }
  ]
}
{
  "request": {
    "status_code": 200,
    "success": true
  },
  "response": [
    {
      "session_id": "redacted",
      "user_agent": "redacted",
      "created_ip": "redacted",
      "created_on": 0,
      "expires_on": 0,
      "updated_on": 0
    },
    {
      "session_id": "redacted",
      "user_agent": "redacted",
      "created_ip": "redacted",
      "created_on": 0,
      "expires_on": 0,
      "updated_on": 0
    },
    {
      "session_id": "redacted",
      "user_agent": "redacted",
      "created_ip": "redacted",
      "created_on": 0,
      "expires_on": 0,
      "updated_on": 0
    },
    {
      "session_id": "redacted",
      "user_agent": "redacted",
      "created_ip": "redacted",
      "created_on": 0,
      "expires_on": 0,
      "updated_on": 0
    },
    {
      "session_id": "redacted",
      "user_agent": "redacted",
      "created_ip": "redacted",
      "created_on": 0,
      "expires_on": 0,
      "updated_on": 0
    }
  ]
}
```

**Comment by andypiper** [comment]
I'm guessing this may be because I have two addresses, so the JSON is an array; and more than one session, ditto (compared to your test). Hope this helps, anyway 😊

**Comment by mcornick** [comment]
Okay, thanks for doing that! I did find one key in the AccountSessions output (UpdatedOn) that I wasn't accounting for (and added it in 0095beb92e22be92c23b08cffcedf85f20bf1168) but otherwise, the output looks identical to the schemas I'm defining.

One potential monkeywrench here is that omg.lol is being DDOSed today. I wonder if you got some garbled JSON due to that? If you try again now, do you still get the errors?

I'll keep digging...

**Comment by mcornick** [comment]
Ah, forgot to ask, and this relevant to the `list account` commands specifically - do you have your email set in your clilol config file? If you don't, it's conceivable that clilol was trying to parse a plain-text error message as JSON. I added code to check for that (as well as the required apikey and address keys as well) but that wasn't there when you found the error earlier.
